version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src
    environment:
      - FLASK_ENV=development
      - FLASK_APP=src/app.py
